// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvjJFgnn-0Ngj_E5uz8ejWSgSaf522fY',
    appId: '1:487706512278:web:699aae5d7435ac8455abb7',
    messagingSenderId: '487706512278',
    projectId: 'attendance-management-sy-28382',
    authDomain: 'attendance-management-sy-28382.firebaseapp.com',
    storageBucket: 'attendance-management-sy-28382.appspot.com',
    measurementId: 'G-QX16FSNVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlzMWZdvAzK631TwYDWsM55aT5X5OQtvU',
    appId: '1:487706512278:android:31c2a9e168892c8855abb7',
    messagingSenderId: '487706512278',
    projectId: 'attendance-management-sy-28382',
    storageBucket: 'attendance-management-sy-28382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMPFR3j2TuQtiiGOarNXLktnQtNGNPy4',
    appId: '1:487706512278:ios:d73c33dda41f0ea055abb7',
    messagingSenderId: '487706512278',
    projectId: 'attendance-management-sy-28382',
    storageBucket: 'attendance-management-sy-28382.appspot.com',
    iosBundleId: 'com.example.attendanceManagementSystem',
  );
}
